name: 刷课
on:
  push:
    branches: [ main ]
#是否开始每天8点定时刷课，若要开启请把下面两行注释去掉
#schedule:
#  - cron: "0 8 * * *"

jobs:
  Start:
    runs-on: ubuntu-latest
    # 提前开启 Node.js 24 模式（可选，和升级Action版本双保险）
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: 拷贝代码
        uses: actions/checkout@v5  # 升级到支持Node 24的v5版本

      - name: 设置python环境
        uses: actions/setup-python@v6  # 升级到支持Node 24的v6版本
        with:
          python-version: '3.11'

      - name: 安装依赖包
        run: |
          pip install -r ./requirements.txt

      - name: Run main.py
        run: python main.py -u 13882965822 -p You19801ing023 -l 257162439
